# MusicEngine Funding Configuration
# Work in progress – currently only contact email available

github: watermann420
custom:
  - name: "Contact for Funding"
    url: "mailto:musicenginebusiness@gmail.com"
